export const products = [
  {
    id: 0,
    name: 'DJI MAVIC 2 PRO',
    slug: 'dji-mavic-2-pro',
    price: 200,
    brand: 'DJI',
    maxPayload: '0.5KG',
    endurace: '31Mins',
    speed: '72km/h',
    usage: 'Surveing and Mapping',
    dimention: {
      height: '84mm',
      width: '91mm',
    },
    totalWeigth: '0.902KG',
    countInStock: 4,
    rating: 3,
    sellerName: 'op',
    image: ['/quadcopter/dji-mavic-2-pro1.jpg','/quadcopter/dji-mavic-2-pro2.jpg','/quadcopter/dji-mavic-2-pro3.jpg'],
    category: 'quadcopter',
  },
  {
    id: 1,
    name: 'DJI FPV',
    slug: 'dji-FPV',
    price: 999,
    brand: 'DJI',
    countInStock: 4,
    maxPayload: '0.5KG',
    endurace: '20mins',
    speed: '72km/h',
    usage: 'Racing',
    dimention: {
      height: '127mm',
      width: '232mm',
    },
    totalWeigth: '0.795KG',
    rating: 5,
    sellerName: 'DJI',
    image: ['/quadcopter/djifpv2.jpeg','/quadcopter/djifpv1.jpg','/quadcopter/dji-fpv3.jpg'],
    category: 'quadcopter',
  },
  {
    id: 2,
    name: 'AGRAS T20',
    slug: 'agras-t20',
    price: 14999,
    brand: 'DJI',
    countInStock: 0,
    maxPayload: '10Kg',
    endurace: '20mins',
    speed: '72km/h',
    usage: 'Agricculture',
    dimention: {
      height: '723mm',
      width: '2213mm',
    },
    totalWeigth: '21.1Kg',
    rating: 2,
    sellerName: 'DJI',
    image: ['/quadcopter/dji-agras-t20-1.jpg','/quadcopter/dji-agras-t20-2.jpg','/quadcopter/dji-agras-t20-3.jpg'],
    category: 'quadcopter',
  },
  {
    id: 3,
    name: 'G15 VTOL UAV',
    slug: 'gi5-vtol-uav',
    price: 1000,
    brand: 'GYUAV',
    maxPayload: '5KG',
    endurace: '210Mins',
    usage: 'Inspection Surveing and Mapping',
    dimention: {
      height: '500mm',
      width: '1500mm',
    },
    speed: '90km/h',
    totalWeigth: '15KG',
    countInStock: 4,
    rating: 5.0,
    sellerName: 'GYUAV',
    image: ['/fixed-wing/g15.jpg'],
    category: 'fixed-wing',
  },
  {
    id: 4,
    name: 'G25 VTOL UAV',
    slug: 'g25-vtol-uav',
    price: 1500,
    brand: 'GYUAV',
    countInStock: 2,
    maxPayload: '10KG',
    endurance: '120Mins',
    usage: 'Surveing and Logistic Delivery',
    dimention: {
      height: '749mm',
      width: '1927mm',
    },
    totalWeigth: '30KG',
    speed: '70km/h',
    rating: 4.5,
    sellerName: 'op',
    image: ['/fixed-wing/g25.jpg'],
    category: 'fixed-wing',
  },
  {
    id: 5,
    name: 'G50 VTOL UAV',
    slug: 'g50-vtol-uav',
    price: 2200,
    brand: 'GYUAV',
    countInStock: 2,
    maxPayload: '15KG',
    endurance: '270Mins',
    usage: 'Security and Inspection',
    dimention: {
      height: '850mm',
      width: '2580mm',
    },
    totalWeigth: '50KG',
    speed: '82km/h',
    rating: 4.5,
    sellerName: 'op',
    image: ['/fixed-wing/g50.jpg'],
    category: 'fixed-wing',
  },
];



export default products